autopkg/scriptingosx-recipes

Python3/Python3.download.recipe, Python3/Python3.install.recipe
URLTextSearcher Processor part of download recipe was failing due to switch from dmg to pkg distribution, added codeSignatureVerification on downloaded .pkg.
(Note: similar to tarball signing for the PSF, they're using an individual’s key, but at least that’s stated officially - Ned shows up [here](https://www.python.org/downloads/), so seems legit).
Added install recipe just ‘cause 😅, bumped recipe version to incorporate new req.s
=> Fix Python3 download regex/path(was dmg, now pkg), add codeSigVerification to download recipe, new .install recipe

VMwareHorizonClient/VMwareHorizonClient.download.recipe
Horizon-recipe stopped working a while ago, fixed it by slightly altering urls
=> Fixed download recipe VMware horizon. Minor url changes.

DjView/DjView.download.recipe, DjView/DjViewURLProvider.py, LaTeXiT/LaTeXiT.download.recipe
- SourceForge now has HTTPS download links, so the URL patterns need to be changed to match both HTTP and HTTPS.
- LaTeXiT appears to have recently added a User-Agent filter to its website
=> Fix DjView and LaTeXiT downloads

VMwareHorizonClient/VMwareHorizonClient.download.recipe
Modified VMwareHorizonClient.download.recipe to use regex to account for changes in the download URL when the product version changes.
=> Updated VMwareHorizonClient.download.recipe

Fetch/Fetch.jss.recipe
Recipe was failing due to Parent Recipe not existing.  This was because of a name change or possible typo.
=> Corrected Parent Recipe Name

VMwareHorizonClient/VMwareHorizonClient.download.recipe
I slightly broadened out the pattern match criteria for VMwareHorizonClient.download, as the Cart code had changed so that there was no match with `\d\dQ\d` anymore. It seems to be fine with `.*`.
=> Opened up the re_pattern for VMwareHorizonClient.download

Python3/Python3.munki.recipe
If you check out http://bugs.python.org/issue24502
the python.org mac packages are being built as metapackages, and unfortunately the contained packages all have version=0.
This causes the python3.munki recipe to create a receipts array of four items that all have the incorrect version number of 0.
Unfortunately, it seems like this issue has been open with the maintainer for awhile, and he seems to think it would be better to just provide an "app installer", although it doesn't seem like they have anyone idea how to pull that off.
I'll mention on that issue that it really just needs to have the versions included, but feel free to jump on there and educate!
Regardless, until then, I updated the python3 recipe to unpack the metapackage and then create an installs item from the Python …
=> Python.org packages have incorrect versions

Audacity/Audacity.pkg.recipe
Update to the Developer ID used to sign Audacity (as of version 2.3.2.0)
=> Change to the signature used to sign Audacity

DjView/DjView.pkg.recipe, Fetch/Fetch_old.pkg.recipe, FileZilla/FileZilla.pkg.recipe, WhatsAppInc/WhatsApp.download.recipe, WhatsAppInc/WhatsApp.install.recipe, WhatsAppInc/WhatsApp.pkg.recipe
Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.
=> Remove NAME variable from app paths

Python3/Python3.download.recipe, Python3/Python3.munki.recipe
Current Python 3.7 will not be updated and also has an incomplete munki pkginfo, because it looks for CFBundleIdentifier in static `/Applications/Python 3.6/Python Launcher.app`.
I duplicated a `URLTextSearcher` processor to save the Python minor version in `%version_minor%` and use that instead.
=> Python3: Use dynamic version_minor in MunkiInstallsItemsCreator

Shellcheck/Shellcheck.install.recipe, Shellcheck/Shellcheck.pkg.recipe
My bad, pkg step was failing on a 'no such file or directory' due to trailing space, don't know how I missed it in the xml bracket 😅
Was also passing bad var (instead of correct, default one output'd from PkgCreator) to Installer
=> fix shellcheck pkg/install recipes

Eclipse/EclipseKepler.download.recipe
Detected and changed HTTPS URLs automatically using my [HTTPS Spotter](https://www.elliotjordan.com/posts/autopkg-https/) script, and then tested all changed recipes manually to ensure download success.
=> Update all available URLs from HTTP to HTTPS

AptanaStudio3/AptanaStudio3.pkg.recipe, Eclipse/EclipseKepler.pkg.recipe, Fetch/Fetch_old.pkg.recipe, FileZilla/FileZilla.pkg.recipe, FirefoxPrefs/FirefoxPrefs.pkg.recipe, ImageJ/ImageJ.pkg.recipe, Shellcheck/Shellcheck.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
=> Adjust PkgCreator arguments

BitTorrent/uTorrent.pkg.recipe, Nomadesk/Nomadesk.pkg.recipe
This pull request removes unused instances of `BUNDLE_ID` from recipe input variables, which will help reduce confusion by new AutoPkg users and simplify overrides created from this point on.
Making `BUNDLE_ID` available as an input variable is a common practice in AutoPkg recipes that use the [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator) processor ([example](https://github.com/autopkg/homebysix-recipes/blob/4fec9244a3af0f9b7c8f61f35a5cd7f4622fb162/soma-zone/LaunchControl.pkg.recipe#L40-L41)). It's likely that these recipes transitioned from PkgCreator to the more streamlined [AppPkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-AppPkgCreator) processor some time ago, but the now-unused input variable for `BUNDLE_ID` was never removed.
Recipe run …
=> Remove unused BUNDLE_ID input var

ImageJ/ImageJ.download.recipe, ImageJ/ImageJ.pkg.recipe
Neither of these recipes have a MunkiImporter process, so the Munki-related input variables serve no purpose and may cause confusion for admins who override the recipes.
=> Remove Munki-related input vars from ImageJ download and pkg recipes

XQuartz/XQuartz.pkg.recipe
Where able, used single character set globbing to find:
* `xquartz`
* `xQuartz`
* `Xquartz` or
* `XQuartz`
Depending upon what the developers output in their pipeline.
Additionally, the path to the payload was updated to change `x11` to `XQuartzComponent`
Added an additional `CodeSignatureVerifier` step for the XQuartz application bundle because I'm paranoid lol.
=> Fix for case fluctuations in XQuartz name and path to payload

Eclipse/EclipseLuna.munki.recipe
The sheagcraig-recipes repository is being deprecated (details here: https://github.com/autopkg/sheagcraig-recipes/issues/71). Many working and/or serviceable recipes have already been [copied](https://github.com/autopkg/homebysix-recipes/pull/414) to the homebysix-recipes repo. This PR changes the parent recipes in your repo to point to the homebysix-recipes version of any affected recipes.
In addition to updating trust info, users of the changed recipes will need to ensure the homebysix-recipes repo is added to their AutoPkg environment (`autopkg repo-add homebysix-recipes`).
=> Adjust parent recipes for sheagcraig-recipes repo deprecation

DjView/DjView.jss.recipe
When autopkg recipe override runs, DjView package always uploads to Jamf with category "Productivity" regardless of CATEGORY key input.
=> Argument does not honor recipe override input

Fetch/FetchVersionFixer.py, SharedProcessors/FileTemplate.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

VMwareHorizonClient/VMwareHorizonClient.download.recipe, VMwareHorizonClient/VMwareHorizonClient.munki.recipe
Forks @Daz-wallace https://github.com/autopkg/scriptingosx-recipes/pull/90 to include an updated `CodeSignatureVerifier` processor as well.
VMware moved from drag and drop DMG to a package. This gets the embedded .app version, copies the package from the DMG, and imports into Munki. Should be a seamless change for those already using the existing recipe.
=> Update VMware Horizon Client Munki recipe for new package based installer
